server:
  port: 8082


spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/orderdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:http://localhost:9296
  # Zipkin
  zipkin:
      base-url: http://localhost:9411/
  logging:
    pattern:
      level: '%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]'
  management:
    tracing:
      sampling:
        probability: 1.0


#eurka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

